receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:

  otlp:
    endpoint: http://otel_collector_services:4317
    tls:
      insecure: true

  otlp/jaeger:
    endpoint: http://jaeger_service:4317
    tls:
      insecure: true
  #     insecure_skip_verify: true

  prometheus:
    endpoint: otel_collector_services:8889

  loki:
    endpoint: "http://loki_service:3100/loki/api/v1/push"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp,otlp/jaeger ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp,loki ]
