urls:
  otel-collector: http://localhost:4318
  postgresql: r2dbc:postgresql://localhost:5432/test_db


server:
  port: 8081
  servlet:
    context-path: /api/users

spring:
  application:
    name: ms-users

  threads:
    virtual:
      enabled: true

  r2dbc:
    url: ${urls.postgresql}
    username: user_test
    password: password_test
  jpa:
    show-sql: true

  sql:
    init:
      data-locations:
        - classpath:db/schema.sql

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      # Configuración para trazas (usando HTTP)
      endpoint: ${urls.otel-collector}
